# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Launch scripts to generate html pages
      run: |
        cd src/scripts/
        python generate_pages.py
    - name: Unit tests
      run: |
        python -m unittest discover -s tests/generate -p "*.py"
    - name: Install html test
      run: |
        sudo apt install -y tidy
    - name: Test html files
      run: |
        tidy -e public/**/*.html 2> tidy_output.log || true
        # Check if there are errors in the tidy output
        if grep -q "Error:" tidy_output.log; then
          echo "HTML validation errors found!"
          exit 1
        else
          echo "Only warnings or clean HTML found."
        fi
    - name: Smoke test
      run: |
          echo 'Testing if the website is up'
          curl -f -I https://sam-rst.github.io/EPSI_Cours-CI_CD/ || exit 1
    - name: Create alias wwwroot about public
      run: |
        ln -s public wwwroot
    - name: Deployement
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: wwwroot
        branch: gh-pages
